### ISSUE TITLE
Initial wireframes and sketches

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/data#5]

**Comment by mushon** [comment]
I'm on it.
Working on flow thumbnails at the moment.

**Comment by mushon** [comment]
Flow 1: [Map and timeline zooms](https://github.com/daat-hamakom/maps/files/31001/Map.and.timeline.zooms.pdf)

Flow 2: [Event Card interaction](https://github.com/daat-hamakom/maps/files/31002/Event.Card.interaction.pdf)

Flow 3: [Expanded filtering](https://github.com/daat-hamakom/maps/files/31005/Expanded.filtering.pdf)

@yuvadm & @josefspr talk to me

**Comment by josefspr** [comment]
Thanks. I'll have time tomorrow evening to look into the sketches 
Few fast question: 
I didn't understand the folding unfolding of the timeline 
Are there clusters on the timeline just like on the map ? 
Does the clicking on a map POI reset the timeline interval ? Why ?
Didn't understand expanded filtering - is each timeline a different filter ? 
What is the relation between the events on the map display and different timelines ?

**Comment by mushon** [comment]
It would be best if we go over this together over phone. But for now:

> I didn't understand the folding unfolding of the timeline 
> Are there clusters on the timeline just like on the map ? 

Yes, but we need to discuss this. It's a bit out of scope, but Yuval and I were considering to bring it back into the scope because it would make the product way better. Let's discuss. 

> Does the clicking on a map POI reset the timeline interval ? Why ?

It doesn't reset the time interval, it only minimizes the extended map interface so you can get back to browsing the map. 

> Didn't understand expanded filtering - is each timeline a different filter ? 

Yes, without filters you see all the events on one timeline. Opening the filtering interface allows you to explore different  timelines separated by different researches, different persons, different organizations … then you can also choose to hide the other POIs from the map and browse it by the filter. 

> What is the relation between the events on the map display and different timelines?

They are closely tied and act together. Click or hover on the map or timeline are equivalent. Hovering a POI on the timeline makes the map POI appear hovered and shows its title too. 

All this and more when we go over it together. ;)

**Comment by josefspr** [comment]
Regarding the expanded filtering: 
We will also still have the static menus for the metadata, right ?
The list of each aggregates can be very large (dozens or hundreds of researches or people), I think we
would need to be able to select and display only part of them, this being part of the filtering.

**Comment by mushon** [comment]
True. We can simply combine them with the free search + order the results by the number on events appearing in the view.

The timelines page would require wireframing.

**Comment by josefspr** [comment]
Will you also add some examples of annotation events in the wireframes ?
Regarding filters: can we save filtered custom maps (maybe as part of odyssey mechanism) ?

**Comment by mushon** [comment]
> Will you also add some examples of annotation events in the wireframes ?

yes, this is still TBD

> Regarding filters: can we save filtered custom maps (maybe as part of odyssey mechanism) ?

I am not sure what you mean by that

**Comment by josefspr** [comment]
that suppose you make a map consisting of an elaborate filtering - it would be nice to save the filter. we didn't add user management in the scopebut even as administrator/researcher I would like to add somecustoms filters/maps using the existing materials.

Date: Fri, 13 Nov 2015 02:06:01 -0800

**Comment by mushon** [comment]
@yuvadm can we achieve that using dynamic URL rewriting?

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by yuvadm** [comment]
@mushon depending on how complex the filter is, we could possibly stash that on the URL, yes.

**Comment by mushon** [comment]
OK, made a ticket to follow this specific issue #8

**Comment by yuvadm** [comment]
:+1:

**Comment by mushon** [comment]
@josefspr & @yuvadm please review expanded wireframes for some of the states in the flow. I would love to get feedback, questions and to know whether there are other states that might need wireframing at this stage.
[daat_flows+wf.pdf](https://github.com/daat-hamakom/maps/files/39099/daat_flows.wf.pdf)

**Comment by yuvadm** [comment]
Looks great, will go over this over the weekend and try to understand the details.

**Comment by mushon** [comment]
This version also takes sorting into account:
[daat_flows+wf.pdf](https://github.com/daat-hamakom/maps/files/39140/daat_flows.wf.pdf)

**Comment by josefspr** [comment]
In general I like the concept of the aggregates and the timelines, it’s a very elegant concept that integrates 3 dimensions: space, time and the aggregates. The expanded aggregate card looks very nice and also the toggle between timelines and cards view.
Questions: 
What does the “title of the expanded timeline” show ? 
Does the search query filter the aggregates or the events or both (this would be confusing) ?
Why are events displayed in the aggregate menu ?
Does “All” mean collapsing all the aggregates to one timeline ?
How do I select to display just a few items from the aggregate list, is it only
by using the search string or maybe also with some kind of select/checkbox ?
I didn’t understand what is the difference between clicking autocomplete and ENTER.
If places is also an aggregate, should we not also add a cover image field for the places ?
In the timeline, how do we deal with many multiple events that have the same time ?

**Comment by mushon** [comment]
Good questions. Answers below.

> What does the “title of the expanded timeline” show ?

It's just that when you focused on a specific item you see its title in the search box.

> Does the search query filter the aggregates or the events or both (this would be confusing) ?
> Why are events displayed in the aggregate menu ?

It filters both, but in case you've searched for "all", an 'event results' timeline would appear first and would aggregate all event results both on that timeline and on the map. If you search for events only you will get all results on the map with the event results timeline minimized. We will need to check whether searching for a query on a filtered search (like people) would also search on the events associated with these people, so if I search for "transformation" on a "people" filter it would bring up the "Kafka" timeline. I think this can be quite easily experimented with (@yuvadm correct me if I'm wrong).

> Does “All” mean collapsing all the aggregates to one timeline ?

no, it means searching on multiple timelines, essentially searching on all the database and accepting whatever response based on the query.

> How do I select to display just a few items from the aggregate list, is it only by using the search string or maybe also with some kind of select/checkbox ?

I am not sure I understand the user-case. Can you give an example?

> I didn’t understand what is the difference between clicking autocomplete and ENTER.

Clicking one of the autocomplete results will take you directly to the aggregate card (or the event card) rather than showing you multiple results in the timelines and the map (which is what you get by hitting ENTER)

> If places is also an aggregate, should we not also add a cover image field for the places ?

No, we can use mini maps for them.

> In the timeline, how do we deal with many multiple events that have the same time ?

we'll do timeline clustering. This will be solved in the visual design phase, coming soon.

**Comment by mushon** [comment]
More updates to the wireframes including some of my answers from above and some more details about card interactions: [daat_flows+wf.pdf](https://github.com/daat-hamakom/maps/files/41026/daat_flows.wf.pdf).
Unless any of you have any more inputs on the structure at this point I would like to move on to the visual design. What say you?

**Comment by yuvadm** [comment]
Generally I like it a lot, and the overall structure makes sense. Because I'm still working on the data model and admin, there isn't much getting done on the front-end of things so it's still hard to get a feel of how it all fits in. Once we're done and happy with the current milestone I'll start planning the work on the interface and see how it fits with our schedule.

**Comment by josefspr** [comment]
looks very nice. I would like to go over a few things, better on phone, available tomorrow (noon) morning or noon ? after we do that I want to show edwin and some other people in data hamakom to get their remarks.

**Comment by mushon** [comment]
Sure. Let's talk tomorrow.

**Comment by mushon** [comment]
@yuvadm please review this addittion to allow advanced filtering through the search query (these are advanced features that would not be explicitly exposed through the GUI):
[daat_flows+wf.pdf](https://github.com/daat-hamakom/maps/files/41422/daat_flows.wf.pdf)

**Comment by yuvadm** [comment]
@mushon which page?

**Comment by mushon** [comment]
@yuvadm I just updated it with a simpler interaction: [daat_flows+wf.pdf](https://github.com/daat-hamakom/data/files/41454/daat_flows.wf.pdf)
See page 8 (Aggregate Card) and then page 10 (Advanced Filtering). 
The flow could be:
- autocomplete title => get one research filtered (page 8: Aggregate Card)
- get prompt to add another title
- click the prompt automagically enters the `+` and activates a second ResearchTitle autocomplete
- clicking the second title enters it into the search box, collapses the first aggregate and shows only these two timelines.
- this can be continued with yet another `+` interaction

@josefspr please also check this as it expands on the interaction we discussed.

**Comment by josefspr** [comment]
very nice, thanks, will have to resend sketches to researchers ...
